CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    availability BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS storage (
    storage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL UNIQUE REFERENCES products(product_id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS store_sales (
    sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id),
    sale_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    quantity INTEGER NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS online_sales (
    sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id),
    sale_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    quantity INTEGER NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS action_logs (
    action_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.referential_constraints
        WHERE constraint_name = 'storage_product_id_fkey'
          AND update_rule = 'CASCADE'
          AND delete_rule = 'CASCADE'
    ) THEN
        ALTER TABLE storage DROP CONSTRAINT IF EXISTS storage_product_id_fkey;
        ALTER TABLE storage
        ADD CONSTRAINT storage_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.referential_constraints
        WHERE constraint_name = 'store_sales_product_id_fkey'
          AND update_rule = 'CASCADE'
          AND delete_rule = 'CASCADE'
    ) THEN
        ALTER TABLE store_sales DROP CONSTRAINT IF EXISTS store_sales_product_id_fkey;
        ALTER TABLE store_sales
        ADD CONSTRAINT store_sales_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.referential_constraints
        WHERE constraint_name = 'online_sales_product_id_fkey'
          AND update_rule = 'CASCADE'
          AND delete_rule = 'CASCADE'
    ) THEN
        ALTER TABLE online_sales DROP CONSTRAINT IF EXISTS online_sales_product_id_fkey;
        ALTER TABLE online_sales
        ADD CONSTRAINT online_sales_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_and_apply_sale()
RETURNS TRIGGER AS $$
DECLARE
    product_is_active BOOLEAN;
    available_quantity INTEGER;
BEGIN
    SELECT availability
    INTO product_is_active
    FROM products
    WHERE product_id = NEW.product_id;

    IF product_is_active IS NULL THEN
        RAISE EXCEPTION 'Product % was not found.', NEW.product_id;
    END IF;

    IF product_is_active IS NOT TRUE THEN
        RAISE EXCEPTION 'Product % is inactive and cannot be sold.', NEW.product_id;
    END IF;

    SELECT quantity
    INTO available_quantity
    FROM storage
    WHERE product_id = NEW.product_id
    FOR UPDATE;

    IF COALESCE(available_quantity, 0) < NEW.quantity THEN
        RAISE EXCEPTION 'Insufficient stock for product %. Requested: %, Available: %.',
            NEW.product_id, NEW.quantity, COALESCE(available_quantity, 0);
    END IF;

    UPDATE storage
    SET quantity = quantity - NEW.quantity
    WHERE product_id = NEW.product_id;

    DELETE FROM storage
    WHERE product_id = NEW.product_id
      AND quantity = 0;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_before_store_sale ON store_sales;
CREATE TRIGGER trg_before_store_sale
BEFORE INSERT ON store_sales
FOR EACH ROW
EXECUTE FUNCTION validate_and_apply_sale();

DROP TRIGGER IF EXISTS trg_before_online_sale ON online_sales;
CREATE TRIGGER trg_before_online_sale
BEFORE INSERT ON online_sales
FOR EACH ROW
EXECUTE FUNCTION validate_and_apply_sale();

INSERT INTO products (product_id, product_name, price, availability)
VALUES
    (1, 'Laptop Pro', 1200.00, TRUE),
    (2, 'Smartphone X', 600.00, TRUE),
    (3, 'Headphones', 150.00, TRUE),
    (4, 'Smartwatch', 250.00, TRUE)
ON CONFLICT (product_id) DO NOTHING;

INSERT INTO storage (product_id, quantity)
VALUES
    (1, 20),
    (2, 30),
    (3, 50),
    (4, 15)
ON CONFLICT (product_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('products', 'product_id'),
    COALESCE((SELECT MAX(product_id) FROM products), 1),
    TRUE
);
